spring.application.name=api
spring.datasource.url=jdbc:mysql://localhost:3306/vollmed_api
spring.datasource.username=root
spring.datasource.password=suasenha123
spring.datasource.driver-class-names=com.mysql.cj.jdbc.Driver

spring.web.error.include-stacktrace=never
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${JWT_SECRET:12345678}